project:
  type: website

website:
  title: "Jason Timm"
  twitter-card: true
  opengraph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jaytimm
      - icon: twitter
        href: https://twitter.com/DrJayTimm

format:
  html:
    theme: flatly.scss
    css: styles.css



