project:
  type: website

website:
  site-url: "https://www.jtimm.net"
  description: "Some technical notes using R."
  google-analytics: "G-T6556WBG2H"
  title: "Jason Timm"
  twitter-card: true
  opengraph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jaytimm
      - icon: twitter
        href: https://twitter.com/DrJayTimm
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo.scss
    css: styles.css



